language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
env:
  - SUITE=unit
  - SUITE=lint
matrix:
  exclude:
    - node_js: "0.10"
      env: SUITE=lint
    - node_js: "0.12"
      env: SUITE=lint
    - node_js: "4"
      env: SUITE=lint
    - node_js: "5"
      env: SUITE=lint
install:
  - npm install
script:
  - npm run $SUITE
